# -*- coding: utf-8 -*-
"""streamlit_checkpoint.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OxCtgqtr1vn6seC0ugzaDPU61bVRUWCB
"""

# Commented out IPython magic to ensure Python compatibility.
# pip install streamlit==1.13.0
# import pandas as pd
# import streamlit as st
# from sklearn import datasets
# from sklearn import ensemble
# ! pip install pyngrok
# %%writefile app.py
# import numpy as np
# import streamlit as st
# import pandas as pd
# from sklearn import datasets
# from sklearn.ensemble import RandomForestClassifier
# 
# st.write(''' # Simple Iris Flower Prediction App''')
# st.sidebar.header('User Input Parameters')
# def user_input_features():
#   sepal_length = st.sidebar.slider('sepal length', 4.3, 7.9, 5.4)
#   sepal_width = st.sidebar.slider('sepal width', 2.0, 4.4, 3.4)
#   petal_length = st.sidebar.slider('petal length', 1.0, 6.9, 1.3)
#   petal_width = st.sidebar.slider('petal width', 0.1, 2.5, 0.2)
# 
#   user_input_data = {'sepal_length': sepal_length,
#                ' sepal_width': sepal_width,
#                'petal_length': petal_length,
#                'petal_width': petal_width}
# 
#   features = pd.DataFrame(user_input_data, index=[0])
#   return features
# df = user_input_features()
# st.subheader('User Input Parameters')
# st.write(df)
# 
# iris = datasets.load_iris()
# X = iris.data
# Y = iris.target
# 
# classifier = RandomForestClassifier()
# classifier.fit(X, Y)
# 
# pred = classifier.predict(df)
# if pred == 0:
#   prediction = "setosa"
# elif pred == 1:
#   prediction = "versicolor"
# elif pred == 2:
#   prediction = "virginica"
# classify = st.button('Classify')
# if classify:
#   st.subheader("The flower type is:")
#   st.write(prediction)